extension Generator {
    enum FieldStorage {
        case value
        case indirectMessage
    }

    struct FieldPlan {
        let field: FieldProto
        let property: String
        let type: String
        let storage: FieldStorage

        var requiresBox: Bool {
            if case .indirectMessage = storage { return true }
            return false
        }
    }

    static func renderExtra(file: FileProto, index: SchemaIndex) throws -> String {
        var output = "// Generated by protoc-gen-pcsw --pcsw_opt=extra. DO NOT EDIT.\nimport ProtoCacheCore\n\n"
        let scope = file.package.isEmpty ? "" : ".\(file.package)"
        for message in file.messageType where !message.options.deprecated && !message.options.mapEntry {
            output += try renderMutable(message: message, fullName: "\(scope).\(message.name)", index: index)
        }
        return String(output.dropLast())
    }

    static let sourceDecl = "    private var _source: Bytes\n"

    static func renderInitializers(emptyValue: String? = nil) -> String {
        let valueInitialization = emptyValue.map { "; _value = \($0)" } ?? ""
        return "    public init() { _source = .empty\(valueInitialization) }\n    public init(_ bytes: Bytes) { _source = bytes }\n"
    }

    static func renderUntouchedSource(view: String, condition: String) -> String {
        var output = "        if \(condition) {\n"
        output += "            return try _source.withBorrowedSpan { bytes in\n"
        output += "                let wordCount = try \(view)._detectProtoCacheWords(bytes)\n"
        output += "                return try _ProtoCacheEncoding.embedded(bytes.slice(byteOffset: 0, count: wordCount * 4), in: buffer)\n"
        output += "            }\n"
        output += "        }\n"
        return output
    }

    static func renderMutable(message: MessageProto, fullName: String, index: SchemaIndex) throws -> String {
        var output = ""
        for nested in message.nestedType where !nested.options.deprecated && !nested.options.mapEntry {
            output += try renderMutable(message: nested, fullName: "\(fullName).\(nested.name)", index: index)
        }
        if isAlias(message) {
            return output + (try renderAlias(message: message, fullName: fullName, index: index))
        }
        let name = "\(swiftType(fullName))Mutable"
        let view = "\(swiftType(fullName))View"
        let fieldPlans = try fieldPlans(message: message, owner: fullName, index: index)
        let slotCount = max(1, Int(fieldPlans.map(\.field.number).max() ?? 1))
        let accessedWordCount = (slotCount + 63) / 64
        let accessedIsEmpty = (0..<accessedWordCount).map { "_accessed[\($0)] == 0" }.joined(separator: " && ")
        output += "public struct \(name): _ProtoCacheMutableEncoding {\n"
        output += sourceDecl
        output += "    private var _accessed: InlineArray<\(accessedWordCount), UInt64> = .init(repeating: 0)\n"
        for plan in fieldPlans {
            let initialValue = defaultMutableValue(plan.field, type: plan.type, index: index)
            if plan.requiresBox {
                output += "    private var _\(plan.property) = _ProtoCacheBox<\(plan.type)>(\(initialValue))\n"
            } else {
                output += "    private var _\(plan.property): \(plan.type) = \(initialValue)\n"
            }
        }
        output += renderInitializers()
        for plan in fieldPlans { output += try renderProperty(plan, view: view, index: index) }
        output += "    public var _isProtoCacheEmpty: Bool {\n"
        for plan in fieldPlans { output += renderEmptyCheck(plan, view: view, index: index) }
        output += "        return true\n    }\n"
        output += "    public func _encodeProtoCache(in buffer: _ProtoCacheBuffer) throws -> Unit {\n"
        output += renderUntouchedSource(view: view, condition: accessedIsEmpty)
        output += "        return try _source.withView(\(view).self) { source in\n"
        output += "            let checkpoint = buffer.checkpoint\n"
        output += "            return try _ProtoCacheEncoding.message(fieldCount: \(slotCount), in: buffer, since: checkpoint) { fields in\n"
        for plan in fieldPlans.reversed() {
            output += try renderEncoding(plan, view: view, index: index)
        }
        output += "            }\n"
        output += "        }\n"
        output += "    }\n"
        output += "}\n\n"
        return output
    }

    static func renderAlias(message: MessageProto, fullName: String, index: SchemaIndex) throws -> String {
        let field = message.field[0]
        let name = "\(swiftType(fullName))Mutable"
        let view = "\(swiftType(fullName))View"
        let type = try mutableType(field, index: index)
        var output = "public struct \(name): _ProtoCacheMutableEncoding {\n"
        output += sourceDecl
        output += "    private var _value: \(type)?\n"
        let emptyValue = mapEntry(field, index: index) == nil ? ".some([])" : ".some(.init())"
        output += renderInitializers(emptyValue: emptyValue)
        let decoded = try ownedAlias(field, view: view, index: index)
        output += "    public var value: \(type) {\n        mutating _read {\n            if _value == nil { _value = \(decoded) }\n            yield _value!\n        }\n        set { _value = newValue }\n        _modify {\n            if _value == nil { _value = \(decoded) }\n            yield &_value!\n        }\n    }\n"
        output += "    public var _isProtoCacheEmpty: Bool {\n        if let value = _value { return value.isEmpty }\n        return _source.withView(\(view).self) { $0.isEmpty }\n    }\n"
        output += "    public func _encodeProtoCache(in buffer: _ProtoCacheBuffer) throws -> Unit {\n"
        output += renderUntouchedSource(view: view, condition: "_value == nil")
        output += try renderContainer(
            field,
            value: "_value!",
            target: "return",
            index: index,
            indent: "        "
        )
        output += "    }\n"
        output += "}\n\n"
        return output
    }

    static func renderProperty(_ plan: FieldPlan, view: String, index: SchemaIndex) throws -> String {
        let field = plan.field
        let property = plan.property
        let id = field.number - 1
        let unaccessed = "_accessed[\(id >> 6)] & (UInt64(1) << \(id & 63)) == 0"
        let markAccessed = "_accessed[\(id >> 6)] |= UInt64(1) << \(id & 63)"
        let decoded = try ownedSource(
            field,
            resultType: plan.type,
            view: view,
            property: property,
            index: index
        )
        var output = "    public var \(property): \(plan.type) {\n"
        if plan.requiresBox {
            output += "        mutating _read {\n            if \(unaccessed) { _\(property) = _ProtoCacheBox(\(decoded)); \(markAccessed) }\n            yield _\(property).value\n        }\n"
            output += "        set { _\(property) = _ProtoCacheBox(newValue); \(markAccessed) }\n"
            output += "        _modify {\n            if \(unaccessed) { _\(property) = _ProtoCacheBox(\(decoded)); \(markAccessed) }\n            _protoCacheEnsureUnique(&_\(property))\n            yield &_\(property).value\n        }\n"
        } else {
            output += "        mutating _read {\n            if \(unaccessed) { _\(property) = \(decoded); \(markAccessed) }\n            yield _\(property)\n        }\n"
            output += "        set { _\(property) = newValue; \(markAccessed) }\n"
            output += "        _modify {\n            if \(unaccessed) { _\(property) = \(decoded); \(markAccessed) }\n            yield &_\(property)\n        }\n"
        }
        return output + "    }\n"
    }

    static func renderEmptyCheck(_ plan: FieldPlan, view: String, index: SchemaIndex) -> String {
        let field = plan.field
        let property = plan.property
        let id = field.number - 1
        let accessed = "_accessed[\(id >> 6)] & (UInt64(1) << \(id & 63)) != 0"
        let nonempty: String
        if field.type == .message && field.label != .repeated && mapEntry(field, index: index) == nil {
            let value = plan.requiresBox ? "_\(property).value" : "_\(property)"
            return "        if \(accessed) { if !\(value)._isProtoCacheEmpty { return false } } else if _source.withView(\(view).self, { $0._protoCacheMessageView.hasField(\(id)) }) { return false }\n"
        }
        if field.label == .repeated || mapEntry(field, index: index) != nil || field.type == .string || field.type == .bytes {
            nonempty = "!value.isEmpty"
        } else if field.type == .enum {
            nonempty = "value.rawValue != 0"
        } else if field.type == .bool {
            nonempty = "value"
        } else {
            nonempty = "value != 0"
        }
        return "        if \(accessed) { let value = _\(property); if \(nonempty) { return false } } else if _source.withView(\(view).self, { $0._protoCacheMessageView.hasField(\(id)) }) { return false }\n"
    }

    static func renderEncoding(_ plan: FieldPlan, view: String, index: SchemaIndex) throws -> String {
        let field = plan.field
        let property = plan.property
        let id = field.number - 1
        var output = "                if _accessed[\(id >> 6)] & (UInt64(1) << \(id & 63)) != 0 {\n"
        if field.type == .message && field.label != .repeated && mapEntry(field, index: index) == nil {
            let value = plan.requiresBox ? "_\(property).value" : "_\(property)"
            output += "                    let value = \(value)\n                    if !value._isProtoCacheEmpty { fields[\(id)] = try value._encodeProtoCache(in: buffer) }\n"
        } else if field.label == .repeated || mapEntry(field, index: index) != nil {
            output += "                    let value = _\(property)\n                    if !value.isEmpty {\n"
            output += try renderContainer(
                field,
                value: "value",
                target: "fields[\(id)] =",
                index: index,
                indent: "                        "
            )
            output += "                    }\n"
        } else {
            let condition: String
            if field.type == .string || field.type == .bytes {
                condition = "!value.isEmpty"
            } else if field.type == .enum {
                condition = "value.rawValue != 0"
            } else if field.type == .bool {
                condition = "value"
            } else {
                condition = "value != 0"
            }
            output += "                    let value = _\(property)\n                    if \(condition) { fields[\(id)] = \(try encodeValue(field, value: "value")) }\n"
        }
        let copyExpression: String
        if isReference(field, index: index) {
            let detector = try detectValue(field, source: "child", depth: "0", index: index)
            copyExpression = "try _ProtoCacheEncoding.copy(original, in: buffer) { child in \(detector) }"
        } else {
            copyExpression = "_ProtoCacheEncoding._copyInline(original)"
        }
        output += "                } else if let original = source._protoCacheMessageView.field(\(id)) {\n"
        output += "                    fields[\(id)] = \(copyExpression)\n"
        output += "                }\n"
        if isReference(field, index: index) {
            output += "                _ProtoCacheEncoding.fold(&fields[\(id)], in: buffer)\n"
        }
        return output
    }

    static func renderContainer(
        _ field: FieldProto,
        value: String,
        target: String,
        index: SchemaIndex,
        indent: String
    ) throws -> String {
        if let entry = mapEntry(field, index: index) {
            let nestedIndent = indent + "    "
            let nestedTarget = target == "return" ? "return" : target
            var output = "\(indent)\(target == "return" ? "return " : "")try \(value)._withDictionary { value in\n"
            output += "\(nestedIndent)let checkpoint = buffer.checkpoint\n"
            output += "\(nestedIndent)\(nestedTarget) try _ProtoCacheEncoding.map(entryCount: value.count, in: buffer, since: checkpoint) { encodedEntries in\n"
            output += "\(nestedIndent)    var entryIndex = 0\n"
            output += "\(nestedIndent)    for entry in value {\n"
            output += "\(nestedIndent)        encodedEntries[entryIndex] = _ProtoCacheMapEntry(key: entry.key._protoCacheKeyBytes, keyUnit: \(try encodeValue(entry.field[0], value: "entry.key")), valueUnit: \(try encodeValue(entry.field[1], value: "entry.value")))\n"
            output += "\(nestedIndent)        entryIndex += 1\n"
            output += "\(nestedIndent)    }\n"
            output += "\(nestedIndent)}\n"
            output += "\(indent)}\n"
            return output
        }
        if field.type == .bool {
            return "\(indent)\(target) try _ProtoCacheEncoding.boolArray(\(value), in: buffer)\n"
        }
        var output = "\(indent)let checkpoint = buffer.checkpoint\n"
        output += "\(indent)\(target) try _ProtoCacheEncoding.array(elementCount: \(value).count, in: buffer, since: checkpoint) { elements in\n"
        output += "\(indent)    for index in \(value).indices { elements[index] = \(try encodeValue(field, value: "\(value)[index]")) }\n"
        output += "\(indent)}\n"
        return output
    }

    static func encodeValue(_ field: FieldProto, value: String) throws -> String {
        switch field.type {
        case .string: "try _ProtoCacheEncoding.string(\(value), in: buffer)"
        case .bytes: "try _ProtoCacheEncoding.byteArray(\(value), in: buffer)"
        case .message: "try \(value)._encodeProtoCache(in: buffer)"
        case .enum: "_ProtoCacheEncoding.scalar(\(value).rawValue)"
        default: "_ProtoCacheEncoding.scalar(\(value))"
        }
    }

    static func ownedAlias(_ field: FieldProto, view: String, index: SchemaIndex) throws -> String {
        let body = try ownedContainer(
            field,
            source: "source",
            owner: "_source",
            resultType: try mutableType(field, index: index),
            index: index
        )
        return "_source.withView(\(view).self) { source in \(body) }"
    }

    static func ownedSource(
        _ field: FieldProto,
        resultType: String,
        view: String,
        property: String,
        index: SchemaIndex
    ) throws -> String {
        if field.label == .repeated || mapEntry(field, index: index) != nil {
            let body = try ownedContainer(
                field,
                source: "source.\(property)",
                owner: "_source",
                resultType: resultType,
                index: index
            )
            return "_source.withView(\(view).self) { source in \(body) }"
        }
        if field.type == .message {
            let mutable = "\(swiftType(field.typeName))Mutable"
            return "{ let owner = _source; let range = owner.withView(\(view).self) { source in let root = source._protoCacheSpan; let nested = source.\(property); let child = nested._protoCacheSpan; return root.byteRange(of: child) }; return \(mutable)(owner.slice(byteOffset: range.lowerBound, count: range.count)) }()"
        }
        let conversion = try ownedValue(field, value: "source.\(property)", owner: "_source")
        return "_source.withView(\(view).self) { source in \(conversion) }"
    }

    static func ownedContainer(
        _ field: FieldProto,
        source: String,
        owner: String,
        resultType: String,
        index: SchemaIndex
    ) throws -> String {
        if let entry = mapEntry(field, index: index) {
            let key = try ownedValue(entry.field[0], value: "key", owner: owner)
            let value = try ownedValue(entry.field[1], value: "value", owner: owner)
            return "var result = \(resultType)(); result.reserveCapacity(\(source).count); \(source).forEach { key, value in result[\(key)] = \(value) }; return result"
        }
        let element = try ownedValue(field, value: "element", owner: owner)
        return "var result: \(resultType) = []; result.reserveCapacity(\(source).count); \(source).forEach { element in result.append(\(element)) }; return result"
    }

    static func ownedValue(
        _ field: FieldProto,
        value: String,
        owner: String
    ) throws -> String {
        switch field.type {
        case .string: "\(value).withUnsafeUTF8 { String(decoding: $0, as: UTF8.self) }"
        case .bytes: "\(value).withUnsafeBytes { Array($0) }"
        case .message: "{ let bytes = \(owner).ownedSlice(of: \(value)._protoCacheSpan); return \(swiftType(field.typeName))Mutable(bytes) }()"
        default: value
        }
    }

    static func mutableType(_ field: FieldProto, index: SchemaIndex) throws -> String {
        if let entry = mapEntry(field, index: index) {
            return "MutableMap<\(try ownedType(entry.field[0])), \(try ownedType(entry.field[1]))>"
        }
        if field.label == .repeated { return "[\(try ownedType(field))]" }
        return try ownedType(field)
    }

    static func defaultMutableValue(_ field: FieldProto, type: String, index: SchemaIndex) -> String {
        if field.label == .repeated || mapEntry(field, index: index) != nil { return ".init()" }
        switch field.type {
        case .string, .bytes, .message:
            return ".init()"
        case .enum:
            return "\(type)(rawValue: 0)"
        case .bool:
            return "false"
        default:
            return "0"
        }
    }

    static func ownedType(_ field: FieldProto) throws -> String {
        switch field.type {
        case .string: "String"
        case .bytes: "[UInt8]"
        case .message: "\(swiftType(field.typeName))Mutable"
        default: try readType(field)
        }
    }

    static func fieldPlans(
        message: MessageProto,
        owner: String,
        index: SchemaIndex
    ) throws -> [FieldPlan] {
        try activeFields(message).map { field in
            FieldPlan(
                field: field,
                property: identifier(lowerCamel(field.name)),
                type: try mutableType(field, index: index),
                storage: isIndirect(owner: owner, field: field, index: index)
                    ? .indirectMessage
                    : .value
            )
        }
    }

    static func isIndirect(owner: String, field: FieldProto, index: SchemaIndex) -> Bool {
        guard field.type == .message,
              field.label != .repeated,
              mapEntry(field, index: index) == nil else { return false }
        return hasDirectPath(from: field.typeName, to: owner, index: index, visited: [])
    }

    static func hasDirectPath(
        from current: String,
        to target: String,
        index: SchemaIndex,
        visited: Set<String>
    ) -> Bool {
        if current == target { return true }
        guard !visited.contains(current),
              let message = index.messages[current],
              !isAlias(message) else { return false }
        var visited = visited
        visited.insert(current)
        for field in activeFields(message)
        where field.type == .message && field.label != .repeated && mapEntry(field, index: index) == nil {
            if hasDirectPath(from: field.typeName, to: target, index: index, visited: visited) {
                return true
            }
        }
        return false
    }
}
