extension Generator {
    static func renderReadonly(file: FileProto, index: SchemaIndex) throws -> String {
        var output = "// Generated by protoc-gen-pcsw. DO NOT EDIT.\nimport ProtoCacheCore\n\n"
        let scope = file.package.isEmpty ? "" : ".\(file.package)"
        for item in file.enumType where !item.options.deprecated {
            output += render(enum: item, fullName: "\(scope).\(item.name)")
        }
        for message in file.messageType where !message.options.deprecated {
            output += try renderReadonly(message: message, fullName: "\(scope).\(message.name)", index: index)
        }
        return String(output.dropLast())
    }

    static func render(enum item: EnumProto, fullName: String) -> String {
        let name = "\(swiftType(fullName))Value"
        var output = "public struct \(name): RawRepresentable, Hashable, Sendable, FieldDecodable {\n"
        output += "    public let rawValue: Int32\n    @inlinable @inline(__always) public init(rawValue: Int32) { self.rawValue = rawValue }\n"
        for value in item.value where !value.options.deprecated {
            output += "    public static let \(identifier(lowerCamel(value.name))) = Self(rawValue: \(value.number))\n"
        }
        output += "    @inlinable @inline(__always) public static func _decodeProtoCache(from field: FieldView) -> Self? { guard let value = field.scalar(Int32.self) else { return nil }; return Self(rawValue: value) }\n"
        output += "    @inlinable @inline(__always) public static func _decodeProtoCache(fromRawWords baseAddress: UnsafeRawPointer, availableByteCount: Int, width: Int, owner: borrowing Span) -> Self? { guard let value = Int32._decodeProtoCache(fromRawWords: baseAddress, availableByteCount: availableByteCount, width: width, owner: owner) else { return nil }; return Self(rawValue: value) }\n}\n\n"
        return output
    }

    static func renderReadonly(message: MessageProto, fullName: String, index: SchemaIndex) throws -> String {
        if message.options.mapEntry { return "" }
        var output = ""
        for item in message.enumType where !item.options.deprecated {
            output += render(enum: item, fullName: "\(fullName).\(item.name)")
        }
        for nested in message.nestedType where !nested.options.deprecated && !nested.options.mapEntry {
            output += try renderReadonly(message: nested, fullName: "\(fullName).\(nested.name)", index: index)
        }
        let name = "\(swiftType(fullName))View"
        let layoutName = "_pcswLayout_\(name)"
        if isAlias(message) {
            let field = message.field[0]
            if let entry = mapEntry(field, index: index) {
                let key = try readType(entry.field[0])
                let value = try readType(entry.field[1])
                output += "public struct \(name): ~Escapable, GeneratedView {\n"
                output += "    public typealias Key = \(key)\n    public typealias Value = \(value)\n"
                output += "    private let _value: MapView<Key, Value>\n"
                output += renderViewStorage(for: "_value._protoCacheSpan", initializer: "_value = MapView(bytes)")
                output += "    public var count: Int { _value.count }\n    public var isEmpty: Bool { _value.isEmpty }\n"
                output += renderMapAccessor(name: "key", type: "Key", borrowed: isBorrowed(entry.field[0]))
                output += renderMapAccessor(name: "value", type: "Value", borrowed: isBorrowed(entry.field[1]))
                output += "    @_lifetime(copy self) public func value(for key: borrowing Key) -> Value? { _value.value(for: key) }\n"
                output += "    public func forEach(_ body: (borrowing Key, borrowing Value) throws -> Void) rethrows { try _value.forEach(body) }\n"
                if entry.field[0].type == .string {
                    output += "    @_lifetime(copy self) public func value(for key: String) -> Value? { guard let position = _value.position(for: key) else { return nil }; return _value.value(at: position) }\n"
                }
            } else {
                output += "public struct \(name): ~Escapable, GeneratedView {\n"
                output += "    public typealias Element = \(try readType(field))\n"
                output += "    private let _value: ArrayView<Element>\n"
                output += renderViewStorage(for: "_value._protoCacheSpan", initializer: "_value = ArrayView(bytes)")
                output += "    public var count: Int { _value.count }\n    public var isEmpty: Bool { _value.isEmpty }\n"
                if isBorrowed(field) {
                    output += "    public subscript(position: Int) -> Element { @_lifetime(copy self) borrowing get { _value[position] } }\n"
                } else {
                    output += "    public subscript(position: Int) -> Element { _value[position] }\n"
                }
                output += "    public func forEach(_ body: (borrowing Element) throws -> Void) rethrows { try _value.forEach(body) }\n"
            }
            output += try renderDetector(message: message, index: index)
            output += "    public static var _protoCacheLayout: _ProtoCacheLayout { \(layoutName) }\n}\n"
            output += "private let \(layoutName) = _ProtoCacheLayout(fullName: \"\(trimDot(fullName))\", fields: [\n"
            output += "    _ProtoCacheFieldLayout(number: 1, kind: \(try metadataKind(field, index: index))),\n], isAlias: true)\n\n"
            return output
        }

        let fields = activeFields(message)
        output += "public struct \(name): ~Escapable, GeneratedView {\n"
        output += "    public let _protoCacheMessageView: MessageView\n"
        output += renderViewStorage(
            for: "_protoCacheMessageView.bytes",
            initializer: "_protoCacheMessageView = MessageView(bytes)",
            inline: true
        )
        if !fields.isEmpty {
            output += "    public enum Field: Int, Sendable {\n"
            for field in fields {
                output += "        case \(identifier(lowerCamel(field.name))) = \(field.number - 1)\n"
            }
            output += "    }\n    @inlinable @inline(__always) public func hasField(_ field: Field) -> Bool { _protoCacheMessageView.hasField(field.rawValue) }\n"
        }
        for field in fields { output += try renderGetter(field, index: index) }
        output += try renderDetector(message: message, index: index)
        output += "    public static var _protoCacheLayout: _ProtoCacheLayout { \(layoutName) }\n}\n"
        output += "private let \(layoutName) = _ProtoCacheLayout(\n    fullName: \"\(trimDot(fullName))\",\n    fields: [\n"
        for field in fields {
            output += "        _ProtoCacheFieldLayout(number: \(field.number), kind: \(try metadataKind(field, index: index))),\n"
        }
        output += "    ]\n)\n\n"
        return output
    }

    static func renderDetector(
        message: MessageProto,
        index: SchemaIndex
    ) throws -> String {
        var output = "    @inline(__always) static func _detectProtoCacheWords(_ bytes: Span, depth: Int = 0) throws -> Int {\n"
        output += "        guard depth <= 100 else { throw ProtoCacheError.recursionLimitExceeded }\n"
        if isAlias(message) {
            output += "        return \(try detectValue(message.field[0], source: "bytes", depth: "depth", index: index))\n"
            output += "    }\n"
            return output
        }

        output += "        let baseWords = try _ProtoCacheEncoding._detectMessageBaseWords(bytes)\n"
        let referencedFields = activeFields(message).reversed().filter {
            isReference($0, index: index)
        }
        if !referencedFields.isEmpty {
            output += "        let view = MessageView(bytes)\n"
            output += "        var detectedWords = baseWords\n"
        }
        for field in referencedFields {
            let id = field.number - 1
            let expression = try detectValue(
                field,
                source: "child",
                depth: "depth + 1",
                index: index
            )
            output += "        if let field = view.field(\(id)) {\n"
            output += "            let end = try _ProtoCacheEncoding._detectReferencedEnd(field, in: bytes) { child in \(expression) }\n"
            output += "            if end == bytes.count / 4 { return end }\n"
            output += "            if end > detectedWords { detectedWords = end }\n"
            output += "        }\n"
        }
        output += referencedFields.isEmpty ? "        return baseWords\n" : "        return detectedWords\n"
        output += "    }\n"
        return output
    }

    static func renderViewStorage(for span: String, initializer: String, inline: Bool = false) -> String {
        let attributes = inline ? "@inlinable @inline(__always) " : ""
        return "    public var _protoCacheSpan: Span { @_lifetime(borrow self) borrowing get { \(span) } }\n" +
            "    @_lifetime(copy bytes) \(attributes)public init(_ bytes: Span) { \(initializer) }\n" +
            "    @_lifetime(copy field) \(attributes)public static func _decodeProtoCache(from field: FieldView) -> Self? { Self(field.objectBytes) }\n" +
            "    @_lifetime(copy owner) \(attributes)public static func _decodeProtoCache(fromRawWords baseAddress: UnsafeRawPointer, availableByteCount: Int, width: Int, owner: borrowing Span) -> Self? { guard let bytes = _protoCacheObjectBytes(fromRawWords: baseAddress, availableByteCount: availableByteCount, width: width, owner: owner) else { return nil }; return Self(bytes) }\n"
    }

    static func renderGetter(_ field: FieldProto, index: SchemaIndex) throws -> String {
        let property = identifier(lowerCamel(field.name))
        let id = field.number - 1
        if let entry = mapEntry(field, index: index) {
            let key = try readType(entry.field[0])
            let value = try readType(entry.field[1])
            return borrowedGetter(
                property,
                type: "MapView<\(key), \(value)>",
                expression: "_protoCacheMessageView.map(\(id))"
            )
        }
        if field.label == .repeated {
            if field.type == .bool {
                return borrowedGetter(
                    property,
                    type: "BoolArrayView",
                    expression: "BoolArrayView(_protoCacheMessageView.bytes(\(id)))"
                )
            }
            let element = try readType(field)
            return borrowedGetter(
                property,
                type: "ArrayView<\(element)>",
                expression: "_protoCacheMessageView.array(\(id))"
            )
        }
        switch field.type {
        case .string:
            return borrowedGetter(property, type: "StringView", expression: "_protoCacheMessageView.string(\(id))")
        case .bytes:
            return borrowedGetter(property, type: "BytesView", expression: "_protoCacheMessageView.bytes(\(id))")
        case .message:
            return borrowedGetter(
                property,
                type: try readType(field),
                expression: ".init(_protoCacheMessageView.message(\(id)).bytes)"
            )
        case .enum:
            return "    @inlinable @inline(__always) public var \(property): \(try readType(field)) { .init(rawValue: _protoCacheMessageView.scalar(\(id), as: Int32.self)) }\n"
        default:
            let type = try readType(field)
            return "    @inlinable @inline(__always) public var \(property): \(type) { _protoCacheMessageView.scalar(\(id), as: \(type).self) }\n"
        }
    }

    static func borrowedGetter(_ property: String, type: String, expression: String) -> String {
        "    @inlinable @inline(__always) public var \(property): \(type) { @_lifetime(copy self) borrowing get { \(expression) } }\n"
    }

    static func renderMapAccessor(name: String, type: String, borrowed: Bool) -> String {
        if borrowed {
            return "    @_lifetime(copy self) public func \(name)(at position: Int) -> \(type) { _value.\(name)(at: position) }\n"
        }
        return "    public func \(name)(at position: Int) -> \(type) { _value.\(name)(at: position) }\n"
    }

    static func isBorrowed(_ field: FieldProto) -> Bool {
        field.type == .string || field.type == .bytes || field.type == .message
    }
}
